create extension if not exists pgcrypto;

create table if not exists flight_quotes (
  id uuid primary key default gen_random_uuid(),
  quote_number text unique,
  status text default 'draft',
  client_name text,
  client_email text,
  client_phone text,
  flight_type text,
  quote_mode text not null,
  time_mode text not null,
  operation_type text not null,
  aircraft_id uuid,
  aircraft_name text,
  aircraft_tail text,
  aircraft_capacity integer,
  aircraft_base text,
  departure_at timestamptz,
  return_at timestamptz,
  passengers integer default 1,
  route_summary text,
  total_distance_nm numeric(10, 2),
  client_flight_hours numeric(8, 2),
  billable_hours numeric(8, 2),
  hourly_rate_usd numeric(12, 2),
  flight_cost_usd numeric(12, 2),
  repositioning_cost_usd numeric(12, 2) default 0,
  return_to_base_cost_usd numeric(12, 2) default 0,
  overnight_cost_usd numeric(12, 2) default 0,
  operational_expenses_usd numeric(12, 2) default 0,
  subtotal_usd numeric(12, 2),
  tax_rate numeric(5, 4) default 0,
  tax_amount_usd numeric(12, 2) default 0,
  total_usd numeric(12, 2),
  exchange_rate numeric(10, 4),
  total_mxn numeric(12, 2),
  notes text,
  calculation_version text default 'v1',
  calculation_snapshot jsonb,
  created_by uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists flight_quote_legs (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references flight_quotes(id) on delete cascade,
  leg_order integer not null,
  leg_type text not null,
  visible_to_client boolean default true,
  from_iata text,
  from_icao text,
  from_airport_name text,
  from_city text,
  from_country text,
  from_latitude numeric(10, 6),
  from_longitude numeric(10, 6),
  to_iata text,
  to_icao text,
  to_airport_name text,
  to_city text,
  to_country text,
  to_latitude numeric(10, 6),
  to_longitude numeric(10, 6),
  distance_nm numeric(10, 2),
  cruise_speed_knots numeric(8, 2),
  estimated_air_time numeric(8, 2),
  block_time numeric(8, 2),
  billable_hours numeric(8, 2),
  minimum_hours_applied boolean default false,
  minimum_hours numeric(8, 2),
  hourly_rate_usd numeric(12, 2),
  amount_usd numeric(12, 2),
  passengers integer,
  created_at timestamptz default now()
);
