<script setup>
import { reactive, ref, watch } from "vue";
import BaseModal from "@/components/ui/BaseModal.vue";
import BaseButton from "@/components/ui/BaseButton.vue";
import { CHANNELS, calculateEstimatedCost } from "../services/responseTemplates.service";

const props = defineProps({ open:Boolean, usage:Object, saving:Boolean });
const emit = defineEmits(["close", "save"]); const errors = ref({});
const form = reactive({ recipient_name:"",recipient_contact:"",channel:"copy",duration_minutes:"",hourly_rate:"",currency:"MXN",delivery_status:"prepared",notes:"" });
watch(()=>[props.open,props.usage],()=>{if(!props.open)return;Object.assign(form,{recipient_name:"",recipient_contact:"",channel:"copy",duration_minutes:"",hourly_rate:"",currency:"MXN",delivery_status:"prepared",notes:"",...(props.usage||{})});errors.value={};},{deep:true,immediate:true});
function submit(){const next={};const minutes=Number(form.duration_minutes),rate=Number(form.hourly_rate);if(!Number.isFinite(minutes)||minutes<=0)next.duration_minutes="Ingresa un tiempo mayor que cero";if(!Number.isFinite(rate)||rate<0)next.hourly_rate="Ingresa una tarifa válida";if(!CHANNELS.includes(form.channel))next.channel="Canal inválido";errors.value=next;if(Object.keys(next).length)return;emit("save",{recipient_name:form.recipient_name.trim()||null,recipient_contact:form.recipient_contact.trim()||null,channel:form.channel,duration_minutes:minutes,hourly_rate:rate,currency:form.currency,delivery_status:form.delivery_status,notes:form.notes.trim()||null});}
</script>
<template><BaseModal :open="open" title="Editar registro de uso" hide-footer max-width="720px" @close="emit('close')"><form class="edit-form" @submit.prevent="submit"><div class="grid"><label><span>Cliente</span><input v-model="form.recipient_name"/></label><label><span>Contacto</span><input v-model="form.recipient_contact"/></label><label><span>Canal *</span><select v-model="form.channel"><option v-for="item in CHANNELS" :key="item">{{ item }}</option></select></label><label><span>Moneda *</span><select v-model="form.currency"><option>MXN</option><option>USD</option></select></label><label><span>Tiempo (minutos) *</span><input v-model="form.duration_minutes" type="number" min="1" step="1"/><small>{{ errors.duration_minutes }}</small></label><label><span>Tarifa por hora *</span><input v-model="form.hourly_rate" type="number" min="0" step="0.01"/><small>{{ errors.hourly_rate }}</small></label><label><span>Estado</span><select v-model="form.delivery_status"><option value="prepared">Preparado</option><option value="sent">Enviado</option><option value="delivered">Entregado</option><option value="failed">Fallido</option></select></label><label class="wide"><span>Observaciones</span><textarea v-model="form.notes" rows="3"/></label></div><div class="cost">Costo estimado: <strong>{{ calculateEstimatedCost(form.duration_minutes,form.hourly_rate).toFixed(2) }} {{ form.currency }}</strong></div><div class="actions"><BaseButton variant="secondary" @click="emit('close')">Cancelar</BaseButton><BaseButton type="submit" :disabled="saving">{{ saving?'Guardando…':'Guardar cambios' }}</BaseButton></div></form></BaseModal></template>
<style scoped>.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.wide{grid-column:1/-1}label>span{display:block;margin:5px 0;color:var(--text-muted);font-size:.8rem;font-weight:800}input,select,textarea{padding:10px 12px}small{color:var(--danger)}.cost{margin-top:16px;padding:14px;border-radius:14px;background:var(--bg-soft);color:var(--text-muted)}.actions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}@media(max-width:640px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.actions{flex-direction:column-reverse}}</style>
